language: c
os:
  - linux
addons:
  apt:
    packages:
      - xmlto
      - libgnutls28-dev
      - libnss3-tools
matrix:
  include:
    - os: linux
      compiler: gcc
      dist: trusty
      env: CONF="--enable-static"
    - os: linux
      compiler: gcc
      dist: trusty
      env: CONF="--enable-shared"
    - os: linux
      compiler: gcc
      dist: trusty
      env: CONF="--with-ssl=openssl"
    - os: linux
      compiler: gcc
      dist: trusty
      env: CONF="--with-ssl=gnutls"
script: ./autogen.sh && ./configure --enable-warnings $CONF && make check
