language: c
os:
  - linux
addons:
  apt:
    packages:
      - xmlto
      - libnss3-tools
      - libproxy-dev
env:
matrix:
  include:
    - os: linux
      compiler: gcc
      dist: trusty
      env: CONF="--enable-static"
    - os: linux
      compiler: gcc
      dist: trusty
      env: CONF="--enable-shared"
    - os: linux
      compiler: gcc
      dist: trusty
      env: CONF="--without-libproxy --without-gssapi --without-zlib"
    - os: linux
      compiler: gcc
      dist: trusty
      env: CONF="--enable-memleak"
    - os: linux
      compiler: gcc
      dist: trusty
      env: CONF="--with-ssl=openssl"
  allow_failures:
    - os: linux
      compiler: gcc
      dist: trusty
      env: CONF="--with-ssl=gnutls"
script: ./autogen.sh && ./configure --enable-warnings $CONF && make check && make docs
