name: Build and test

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        conf-shared: [--enable-static, --enable-shared ]
        conf-xml: [--with-expat, --with-libxml2 ]
        conf-ssl: [--without-ssl, --with-ssl=openssl, --with-ssl=gnutls]
        conf-memleak: [--disable-memleak, --enable-memleak]
        conf-debug: [--enable-debug, --disable-debug]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./autogen.sh
    - run: case ${{matrix.conf-ssl}} in
           *gnutls) sudo apt-get -y install libgnutls28-dev gnutls-bin xmlto ;;
           esac
    - run: ./configure ${{matrix.conf-shared}} ${{matrix.conf-xml}} 
                       ${{matrix.conf-ssl}} ${{matrix.conf-memleak}}
                       ${{matrix.conf-debug}}
    - run: make
    - run: make check
